
var yubikey = require('./yubikey.js');

// Replace with your Yubico API Id and Key
yubikey.apiId = 1234;
yubikey.apiKey = 'ABCDEFGHIJKLMNOP=';

var otp = 'abcdefghijklmnoprrhkbclcjucfnudfidvffdkclukfuknnl'; // Generated by Yubikey

yubikey.verify(otp, function(isValid, message) {
	
	if(isValid) {
		console.log('The Yubikey OTP is valid.');
	} else {
		console.log(message);
	}
	
});