
var yubikey = require('./yubikey.js');

// Replace with your Yubico API id and signature key
yubikey.apiId = 1234; // Required
yubikey.apiKey = 'eXViaWNvIHNpZ25hdHVyZSBrZXk='; // Optional, will add HMAC-SHA-1 signature in requests and verify signature in response when set

var otp = 'cccccccabccrgjtrhkbhtleicuututefevkdijfutgud'; // OTP generated by Yubikey

yubikey.verify(otp, function(isValid, message) {
	
	if(isValid) {
		console.log('The Yubikey OTP is valid.');
	} else {
		console.log(message);
	}
	
});